language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "14"
script:
  - yarn build:production
  notifications:
    email:
      recipients:
        - krlosaren@gmail.com
      on_success: always
      on_failure: always
      slack: tropic-lab:55dVeN7C5gxptpxz7gNkY6bE
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
branch: master
