language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - "14"
git:
  depth: 3
script:
  - yarn build:production
deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
branch: master
